general:
  env: "car_racing"
  device : "cuda"

models:
  encoder:
    cnn:
      stride: 2
      activation: "sigmoid"
    mlp:
      n_layers: 3
      d_hidden: 124
      d_out: 16
    rnn:
      n_blocks: 8
      
